.PHONY: task1 task2 task3 clean

task1:
	$(MAKE) -C task1

task1.solution:
	$(MAKE) -C task1 -f Makefile.solution solution

task1.profile:
	$(MAKE) -C task1 profile

task2:
	$(MAKE) -C task2

task2.solution:
	$(MAKE) -C task2 solution

task2.profile:
	$(MAKE) -C task2 profile 

task3:
	$(MAKE) -C task3

task3.solution:
	$(MAKE) -C task3 solution

task3.profile:
	$(MAKE) -C task3 profile

clean:
	$(MAKE) -C task1 clean
	$(MAKE) -C task2 clean
	$(MAKE) -C task3 clean

